### ISSUE TITLE
Cannot detect clang version on macOS 10.14.4 

### ISSUE THREAD

**Issue by jzwolak** [bachev/mira#1]
$ ./bootstrap.sh
    $ ./configure
    ...
    
    checking dependency style of clang++... gcc3
    
    When using clang, you need to have a version >= 3.5. You have only version, aborting.

I checked `configure.ac` and found the line that retrieves the clang version does not work.

    $ clang --version | head -1 | cut -f 3 -d ' '
    version

Because

    $ clang --version
    Apple LLVM version 10.0.1 (clang-1001.0.46.4)
    Target: x86_64-apple-darwin18.5.0
    Thread model: posix
    InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

There is an `autoconf` macro for detecting C++14 support, which seems to be the purpose of checking the clang version. So rather than check the clang version, how about using the autoconf macro for C++14 support? The macro is `AX_CXX_COMPILE_STDCXX_14`.

Unfortunately, I cannot figure out how to use this macro, so I decided to file an issue rather than make the change myself and follow it with a pull request.

**Comment by DrMicrobit** [comment]
Something which did not make it into the documentation: for compiling on MacOS, you *have* to follow the installation/compilation guide down to the very last instruction. In your case, you did not install/use the clang version from homebrew.

The reason is not that the Apple supplied version would not compile and link, it's because the executable compiled with the Apple version and linked with libraries from homebrew will produce a segfault right at the start. I have never been able to find out why and gave up trying to use the Apple clang.

Unfortunately, the current "fix" for this issue will be documenting this behaviour; and a change in autoconf to stop as soon as it sees an Apple version of clang.

**Comment by bjkramerumnedu** [comment]
I'm also having a similar issue on my iMac...was a solution developed to deal with this?

I'm trying to install Mira on my computer in order to run Jorg, which is a MAG circularization method that requires Mira.
